- stack depth
- pritnf order
- stack interface
- Big-O
- find the Nth node from beginning in Single Linked list
- find the Nth node from last in Single Linked list
- find the mid node in linked list
- find the linked list of string of char is palindrome.
